name: 'Update DevCycle Bucketing WASM Binary'
description: 'Update DevCycle Bucketing WASM Binary'

inputs:
  pin-version:
    description: Pinned version. If not specified, will use latest version.
    default: "@latest"
    required: true
  wasm-file-path:
    required: true
    description: Path to the WASM file to manage. Must be the repo root based path.

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Update WASM
      shell: bash
      env:
        BUCKETING_LIB_VERSION: ${{ inputs.pin-version }}
        WASM_FILE_PATH: ${{ inputs.wasm-file-path }}
      run: |
        if [[ -z "$USE_LATEST_BUCKETING_LIB" ]]; then
          if [[ -z "$BUCKETING_LIB_VERSION" ]]; then
            echo "BUCKETING_LIB_VERSION is not set"
            exit 1
          fi
          echo "Using BUCKETING_LIB_VERSION: $BUCKETING_LIB_VERSION"
          BUCKETING_LIB_VERSION="@${BUCKETING_LIB_VERSION}"
        else
          BUCKETING_LIB_VERSION=""
        fi          
        if [[ -z "$WASM_FILE_PATH" ]]; then
          echo "WASM_FILE_PATH is not set"
          exit 1
        fi
        curl -o "${WASM_FILE_PATH}" "https://unpkg.com/@devcycle/bucketing-assembly-script$BUCKETING_LIB_VERSION/build/bucketing-lib.release.wasm"
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update WASM binary to ${{ inputs.node-version }}"
        commit_options: '--no-verify'
        branch: ${{ github.head_ref }}
        file_pattern: '*.wasm'